# **Week 5 - Homework (NumPy, Pandas)**

## **1 - What does Pandas stand for?**
### Pandas stands for either Panel Data or Python Data Analysis

## **2 - What are the 2 collections used in Pandas?**
### Two collections used in Pandas are Series and DataFrame

## **3 - Name 4 things Pandas can do for us.**
### 1. Data Cleansing
### 2. Data normalization
### 3. Data visualization
### 4. Data inspection

## **4 - To permanently sort a DataFrame, which keyword should one use with the `df.sort()` method?**
### The keyword to use is 'inplace'

## **5 - What is a CSV?**
### A CSV is a comma seperated file

## **6 - When cleaning data what values do we not like in our data?**
### We do not like NULLS in the dataframe

#### **Coding Exercise:**

In [7]:
# 7. Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). You can use the reshape method -- `.reshape()` 

import numpy as np

original_array = np.arange(12)

# Reshaped
new_array = original_array.reshape(2, 3, 2)

print(new_array)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [12]:
# 8. Use NumPy `.linspace()` to create an array with 6 linearly spaced values between 0 and 20

import numpy as np

my_array = np.linspace(0, 20, 6)

print(my_array)

[ 0.  4.  8. 12. 16. 20.]


In [13]:
# 9. Make a Deep Copy of the above array

import numpy as np

my_array = np.linspace(0, 20, 6)

my_array_copy = np.copy(my_array)

print(my_array_copy)

[ 0.  4.  8. 12. 16. 20.]


In [15]:
# 10. Concatenate these 3 arrays into a new array named 'newArray'...
#    ```python
#            ([[25, 16]])
#            ([[11, 2], [13, 4]])
#            ([[7, 81], [5, 6], [11, 12]])
#    ```

import numpy as np

array1 = np.array([[25, 16]])
array2 = np.array([[11, 2], [13, 4]])
array3 = np.array([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((array1, array2, array3), axis=0)

print(newArray)

[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [16]:
# 11. Sort 'newArray' in order into 'sortedArray'

import numpy as np

sortedArray = np.sort(newArray)

print(sortedArray)

[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [23]:
# 12. Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables. Using the 'reshapedArray' from number 7 for this. 

import numpy as np

array_slice_1 = new_array[0]
array_slice_2 = new_array[1]
array_slice_3 = new_array[:, 0, :]
array_slice_4 = new_array[:, 1, :]

print("Array Slice 1:")
print(array_slice_1)
print("Array Slice 2:")
print(array_slice_2)
print("Array Slice 3:")
print(array_slice_3)
print("Array Slice 4:")
print(array_slice_4)



Array Slice 1:
[[0 1]
 [2 3]
 [4 5]]
Array Slice 2:
[[ 6  7]
 [ 8  9]
 [10 11]]
Array Slice 3:
[[0 1]
 [6 7]]
Array Slice 4:
[[2 3]
 [8 9]]


In [5]:
# 13. Combined and sort the following arrays into one called 'comboArray' ...
#    one = ([10, 11, 12, 13, 14, 15, 16, 17])
#    two = ([20, 21, 22, 23, 24, 25, 26, 27])
#    three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

import numpy as np

one = np.array([10, 11, 12, 13, 14, 15, 16, 17])
two = np.array([20, 21, 22, 23, 24, 25, 26, 27])
three = np.array([0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.concatenate((one, two, three))

comboArray = np.sort(comboArray)

print(comboArray)

[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


In [8]:
# 14. Take 'comboArray' and perform the following slicing activities:

import numpy as np

print(comboArray)

#print sec1 - the 2nd element
sec1 = comboArray[1]
print("sec1:", sec1)

#print sec2 - all elements from the 3rd element to the last
sec2 = comboArray[2:]
print("sec2:", sec2)

#print sec3 - all elements from the 4th to the 14th elements
sec3 = comboArray[3:14]
print("sec3:", sec3)

#print sec4 - the last 6 elements
sec4 = comboArray[-6:]
print("sec4:", sec4)

#print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
sec5 = comboArray[:15]  # Reverse the order to get the first 16 elements
print("sec5:", sec5)

#print sec6 - from #20 every even element to the end
sec6 = comboArray[20::2]
print("sec6:", sec6)

#print sec7 - from the last element moving forward, every 5th element.
sec7 = comboArray[::-5][::-1]  # Reverse the order to get the forward sequence
print("sec7:", sec7)

[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
sec1: 1
sec2: [ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
sec3: [ 3  4  5  6  7 10 11 12 13 14 15]
sec4: [22 23 24 25 26 27]
sec5: [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16]
sec6: [24 26]
sec7: [ 3 10 15 22 27]


In [42]:
# 15. Using Series, create a DataFrame that looks like this:

# Ingredients	Quantity	Unit
# Flour	4	cups
# Milk	1	cup
# Eggs	2	large
# Spam	1	can
# Name: Dinner, dtype: object

import pandas as pd

data = {
    'Ingredients': ['Flour', 'Milk', 'Eggs', 'Spam'],
    'Quantity': [4, 1, 2, 1],
    'Unit': ['cups', 'cup', 'large', 'can']
}

df = pd.DataFrame(data)
df.name = 'Dinner'

print("Dinner\n", df)


Dinner
   Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can


In [43]:
# 16. Take this data and create a DataFrame named studentData

#    {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
#        'Height': [5.1, 6.2, 5.1, 5.2],
#       'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
#       'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
#       'Age': [21, 23, 24, 21],
#       'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
#       'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
#   }

import pandas as pd

data = {
    'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
    'Height': [5.1, 6.2, 5.1, 5.2],
    'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
    'Address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
    'Age': [21, 23, 24, 21],
    'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
    'Sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
}

studentData = pd.DataFrame(data)

print("Student Data\n", studentData)


Student Data
       Name  Height Qualification  Address  Age        Pets           Sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket


In [60]:
# 17. Add a new column to the DataFrame with the following deserts: ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

import pandas as pd

data = {
    'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
    'Height': [5.1, 6.2, 5.1, 5.2],
    'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
    'Address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
    'Age': [21, 23, 24, 21],
    'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
    'Sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
}

studentData = pd.DataFrame(data)
print("Student Data\n", studentData) 

deserts = ['Ice Cream', 'Cashew Fudge', 'waffels', 'Carrot Halwa']

studentData['Desert'] = deserts
print("\nStudentData with Desert\n", studentData)

Student Data
       Name  Height Qualification  Address  Age        Pets           Sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket

StudentData with Desert
       Name  Height Qualification  Address  Age        Pets           Sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

         Desert  
0     Ice Cream  
1  Cashew Fudge  
2       waffels  
3  Carrot Halwa  


In [70]:
# 18. Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"

import pandas as pd

data = {
    'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
    'Height': [5.1, 6.2, 5.1, 5.2],
    'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
    'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
    'Age': [21, 23, 24, 21],
    'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
    'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket'],
    'deserts': ['ice cream', 'Cashew Fudge', 'waffles', 'Carrot Halwa']
}

# Create a DataFrame from the data dictionary
studentData = pd.DataFrame(data)

# Sort the DataFrame by 'Name' and then 'address' in ascending order
studentData = studentData.sort_values(by=['Name', 'address'], ascending=[True, True])

print(studentData)

      Name  Height Qualification  address  Age        Pets           sport  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

        deserts  
3  Carrot Halwa  
2       waffles  
0     ice cream  
1  Cashew Fudge  


In [73]:
# 19. Save this DataFrame here below to disc as a .CSV file with the name cows_and_goats.csv:

import pandas as pd

df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])

# Save the DataFrame as a CSV file
df.to_csv('cows_and_goats.csv')


In [74]:
# 20. (A) Using Pandas, make your own .CSV file with data on vegetables and save it. (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.

import pandas as pd

# Create a DataFrame with data on vegetables
data = {
    'Vegetable': ['Carrot', 'Broccoli', 'Tomato', 'Spinach', 'Bell Pepper'],
    'Color': ['Orange', 'Green', 'Red', 'Green', 'Yellow'],
    'Taste': ['Sweet', 'Sandy', 'Sweet', 'Mild', 'Sweet'],
    'Price per Pound': [1.5, 2.0, 1.0, 1.2, 1.8]
}

vegetables_df = pd.DataFrame(data)
vegetables_df.to_csv('vegetables.csv', index=False)

# Make changes to the DataFrame, increasing prices for inflation by 40%
vegetables_df['Price per Pound'] = vegetables_df['Price per Pound'] * 1.4

vegetables_df.to_csv('inflation_vegetables.csv', index=False)
